# Generated by Django 3.2.20 on 2025-10-30 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=100)),
                ('date_reported', models.DateField()),
                ('form_completed_by', models.CharField(max_length=200)),
                ('health_facility_code', models.CharField(max_length=50)),
                ('case_source', models.CharField(max_length=70)),
                ('reporting_method', models.CharField(max_length=70)),
            ],
        ),
    ]
