# Generated by Django 3.2 on 2026-01-23 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20260122_1348'),
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='facility',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility', to='patients.patientcase'),
        ),
    ]
