# Generated by Django 3.2 on 2026-01-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_auto_20260123_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='date_reported',
            field=models.DateField(blank=True, null=True),
        ),
    ]
