# Generated by Django 3.2.20 on 2025-10-30 07:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('disease', models.CharField(max_length=200)),
                ('date_of_onset', models.DateField(blank=True, null=True)),
                ('case_classification', models.CharField(max_length=100)),
                ('symptoms', models.CharField(max_length=200)),
                ('outcome', models.CharField(max_length=100)),
                ('triage_level', models.CharField(max_length=100)),
                ('diagnosis_type', models.CharField(max_length=100)),
                ('final_case_classification', models.CharField(max_length=100)),
                ('admission_status', models.CharField(max_length=100)),
                ('contact_with_confirmed_case', models.BooleanField(default=False)),
                ('recent_travel_history', models.BooleanField(default=False)),
                ('travel_destination', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
