# Generated by Django 3.2 on 2026-01-31 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_auto_20260122_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalcase',
            name='admission_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalcase',
            name='case_classification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalcase',
            name='diagnosis_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalcase',
            name='disease',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalcase',
            name='final_case_classification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalcase',
            name='symptoms',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalcase',
            name='triage_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
