# Generated by Django 4.0.5 on 2025-07-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('diagnosis_date', models.DateField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('treatment_type', models.CharField(blank=True, max_length=100)),
                ('parasite_type', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
