# Generated by Django 3.2.20 on 2025-10-31 08:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epidemiological_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('environmental_risk_factors', models.CharField(blank=True, max_length=100, null=True)),
                ('exposure_source', models.CharField(blank=True, max_length=200, null=True)),
                ('cluster_related', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
