# Generated by Django 3.2 on 2026-01-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0002_auto_20260123_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='follow_up_plan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='procedures_done',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='referral_facility',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_given',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
