# Generated by Django 3.2.20 on 2025-10-30 09:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveillanceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('reporting_week_number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('date_reported', models.DateField()),
                ('notifier_signature', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('supervisor_comments', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
