# Generated by Django 3.2 on 2026-01-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance_info', '0003_alter_surveillanceinfo_date_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveillanceinfo',
            name='reporting_week_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='surveillanceinfo',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
