# Generated by Django 3.2.20 on 2025-10-31 09:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outcome_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('outcome', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_outcome', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
