# Generated by Django 3.2.20 on 2025-10-30 08:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('specimen_collected', models.BooleanField(default=False)),
                ('date_specimen_collected', models.DateField(blank=True, null=True)),
                ('specimen_type', models.CharField(blank=True, max_length=100, null=True)),
                ('lab_name', models.CharField(blank=True, max_length=200, null=True)),
                ('specimen_sent_to_lab', models.BooleanField(default=False)),
                ('lab_result', models.CharField(blank=True, max_length=200, null=True)),
                ('lab_tests_ordered', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
