# Generated by Django 5.2.4 on 2025-07-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='severity',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
