# Generated by Django 5.2.4 on 2025-09-25 16:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patientcase_delete_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcase',
            name='patient_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
    ]
