# Generated by Django 3.2 on 2026-01-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20260122_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcase',
            name='id',
        ),
        migrations.AlterField(
            model_name='patientcase',
            name='patient_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
